{
 "title": "Observability lab dashboard",
 "description": "This Grafana dashboard monitors the health and performance of a Linux system using Prometheus and Node Exporter. It provides real-time visualization for key system metrics.",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "clamp_min(100*(1 - (avg by(instance)(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])))),0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes-node_memory_MemAvailable_bytes)/node_memory_MemTotal_bytes)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Uptime (Seconds)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds-node_boot_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}